# 1. Data Understanding and exploration

In [69]:
import warnings
warnings.filterwarnings('ignore')

In [70]:
# Import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
# read dataset
missing_val = ['?']
df = pd.read_csv("adult.csv",na_values=missing_val)

In [72]:
# the top five rows of dataset
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18        NaN  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                NaN    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [73]:
# the bottom five rows of dataset
df.tail()

age     workclass  fnlwgt   education  educational-num  \
48837   27       Private  257302  Assoc-acdm               12   
48838   40       Private  154374     HS-grad                9   
48839   58       Private  151910     HS-grad                9   
48840   22       Private  201490     HS-grad                9   
48841   52  Self-emp-inc  287927     HS-grad                9   

           marital-status         occupation relationship   race  gender  \
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K

In [74]:
# Display the statistical analysis of numerical column
df.describe()

age        fnlwgt  educational-num  capital-gain  \
count  48842.000000  4.884200e+04     48842.000000  48842.000000   
mean      38.643585  1.896641e+05        10.078089   1079.067626   
std       13.710510  1.056040e+05         2.570973   7452.019058   
min       17.000000  1.228500e+04         1.000000      0.000000   
25%       28.000000  1.175505e+05         9.000000      0.000000   
50%       37.000000  1.781445e+05        10.000000      0.000000   
75%       48.000000  2.376420e+05        12.000000      0.000000   
max       90.000000  1.490400e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  48842.000000    48842.000000  
mean      87.502314       40.422382  
std      403.004552       12.391444  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [75]:
# how many rows and columns there in dataset
df.shape

(48842, 15)

In [76]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
age                48842 non-null int64
workclass          46043 non-null object
fnlwgt             48842 non-null int64
education          48842 non-null object
educational-num    48842 non-null int64
marital-status     48842 non-null object
occupation         46033 non-null object
relationship       48842 non-null object
race               48842 non-null object
gender             48842 non-null object
capital-gain       48842 non-null int64
capital-loss       48842 non-null int64
hours-per-week     48842 non-null int64
native-country     47985 non-null object
income             48842 non-null object
dtypes: int64(6), object(9)
memory usage: 3.9+ MB
None


In [77]:
total_rows = len(df)
del_row = df.isnull().any(axis = 1).sum()
print(total_rows, del_row)

48842 3620


In [78]:
# rows with atleast one missing value
df.isnull().any(axis = 1)

0        False
1        False
2        False
3        False
4         True
         ...  
48837    False
48838    False
48839    False
48840    False
48841    False
Length: 48842, dtype: bool

In [79]:
# remove all the missing values by removing the rows where missing value occur
df.dropna(axis = 0, how = 'any', inplace=True)
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
5   34    Private  198693          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
5      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
5              30  United-States  <=50K

In [80]:
current_rows = len(df)
print(current_rows)

45222


# 2. Data Preparation

In [81]:
# remove fnlwgt column
df.drop(['fnlwgt'] , axis=1, inplace=True)
df.head()

age  workclass     education  educational-num      marital-status  \
0   25    Private          11th                7       Never-married   
1   38    Private       HS-grad                9  Married-civ-spouse   
2   28  Local-gov    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  Some-college               10  Married-civ-spouse   
5   34    Private          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
5      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
5              30  United-States  <=50K

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 14 columns):
age                45222 non-null int64
workclass          45222 non-null object
education          45222 non-null object
educational-num    45222 non-null int64
marital-status     45222 non-null object
occupation         45222 non-null object
relationship       45222 non-null object
race               45222 non-null object
gender             45222 non-null object
capital-gain       45222 non-null int64
capital-loss       45222 non-null int64
hours-per-week     45222 non-null int64
native-country     45222 non-null object
income             45222 non-null object
dtypes: int64(5), object(9)
memory usage: 3.6+ MB


In [83]:
# sperating target and input variable
target = df['income']
inputs = df.drop('income',axis=1)

In [84]:
categorical = inputs.select_dtypes(include = ['object'])
categorical.head()

workclass     education      marital-status         occupation  \
0    Private          11th       Never-married  Machine-op-inspct   
1    Private       HS-grad  Married-civ-spouse    Farming-fishing   
2  Local-gov    Assoc-acdm  Married-civ-spouse    Protective-serv   
3    Private  Some-college  Married-civ-spouse  Machine-op-inspct   
5    Private          10th       Never-married      Other-service   

    relationship   race gender native-country  
0      Own-child  Black   Male  United-States  
1        Husband  White   Male  United-States  
2        Husband  White   Male  United-States  
3        Husband  Black   Male  United-States  
5  Not-in-family  White   Male  United-States

In [85]:
numerical  = inputs.select_dtypes(include = ['int64','float'])
numerical.head()

age  educational-num  capital-gain  capital-loss  hours-per-week
0   25                7             0             0              40
1   38                9             0             0              50
2   28               12             0             0              40
3   44               10          7688             0              40
5   34                6             0             0              30

In [86]:
# scaling the numerical featues 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_num = pd.DataFrame(scaler.fit_transform(numerical),columns=numerical.columns)
df_num.head()

age  educational-num  capital-gain  capital-loss  hours-per-week
0 -1.024983        -1.221559     -0.146733      -0.21878       -0.078120
1 -0.041455        -0.438122     -0.146733      -0.21878        0.754701
2 -0.798015         0.737034     -0.146733      -0.21878       -0.078120
3  0.412481        -0.046403      0.877467      -0.21878       -0.078120
4 -0.344079        -1.613277     -0.146733      -0.21878       -0.910942

In [87]:
# Encoding the categorical features
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse=False)
df_cat=pd.DataFrame(ohe.fit_transform(categorical),columns=ohe.get_feature_names(categorical.columns))
df_cat.head()

workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                    0.0                  0.0                1.0   
1                    0.0                  0.0                1.0   
2                    0.0                  1.0                0.0   
3                    0.0                  0.0                1.0   
4                    0.0                  0.0                1.0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  workclass_State-gov  \
0                     0.0                         0.0                  0.0   
1                     0.0                         0.0                  0.0   
2                     0.0                         0.0                  0.0   
3                     0.0                         0.0                  0.0   
4                     0.0                         0.0                  0.0   

   workclass_Without-pay  education_10th  education_11th  education_12th  ...  \
0                    0.0             0.0             1.0             0.0  ...   
1                    0.0             0.0             0.0             0.0  ...   
2                    0.0             0.0             0.0             0.0  ...   
3                    0.0             0.0             0.0             0.0  ...   
4                    0.0             1.0             0.0             0.0  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                      0.0                         0.0   
1                      0.0                         0.0   
2                      0.0                         0.0   
3                      0.0                         0.0   
4                      0.0                         0.0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                      0.0                   0.0                    0.0   
1                      0.0                   0.0                    0.0   
2                      0.0                   0.0                    0.0   
3                      0.0                   0.0                    0.0   
4                      0.0                   0.0                    0.0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                      0.0                             0.0   
1                      0.0                             0.0   
2                      0.0                             0.0   
3                      0.0                             0.0   
4                      0.0                             0.0   

   native-country_United-States  native-country_Vietnam  \
0                           1.0                     0.0   
1                           1.0                     0.0   
2                           1.0                     0.0   
3                           1.0                     0.0   
4                           1.0                     0.0   

   native-country_Yugoslavia  
0                        0.0  
1                        0.0  
2                        0.0  
3                        0.0  
4                        0.0  

[5 rows x 98 columns]

In [88]:
df = pd.concat([df_num, df_cat], axis=1)
df.head()

age  educational-num  capital-gain  capital-loss  hours-per-week  \
0 -1.024983        -1.221559     -0.146733      -0.21878       -0.078120   
1 -0.041455        -0.438122     -0.146733      -0.21878        0.754701   
2 -0.798015         0.737034     -0.146733      -0.21878       -0.078120   
3  0.412481        -0.046403      0.877467      -0.21878       -0.078120   
4 -0.344079        -1.613277     -0.146733      -0.21878       -0.910942   

   workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                    0.0                  0.0                1.0   
1                    0.0                  0.0                1.0   
2                    0.0                  1.0                0.0   
3                    0.0                  0.0                1.0   
4                    0.0                  0.0                1.0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  ...  \
0                     0.0                         0.0  ...   
1                     0.0                         0.0  ...   
2                     0.0                         0.0  ...   
3                     0.0                         0.0  ...   
4                     0.0                         0.0  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                      0.0                         0.0   
1                      0.0                         0.0   
2                      0.0                         0.0   
3                      0.0                         0.0   
4                      0.0                         0.0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                      0.0                   0.0                    0.0   
1                      0.0                   0.0                    0.0   
2                      0.0                   0.0                    0.0   
3                      0.0                   0.0                    0.0   
4                      0.0                   0.0                    0.0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                      0.0                             0.0   
1                      0.0                             0.0   
2                      0.0                             0.0   
3                      0.0                             0.0   
4                      0.0                             0.0   

   native-country_United-States  native-country_Vietnam  \
0                           1.0                     0.0   
1                           1.0                     0.0   
2                           1.0                     0.0   
3                           1.0                     0.0   
4                           1.0                     0.0   

   native-country_Yugoslavia  
0                        0.0  
1                        0.0  
2                        0.0  
3                        0.0  
4                        0.0  

[5 rows x 103 columns]

In [89]:
# split into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df,\
                                                   target,\
                                                   test_size = 0.25,\
                                                   random_state = 0)

In [90]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(33916, 103) (33916,)
(11306, 103) (11306,)


# 3. Train the model on Training Data


In [91]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

# 4. Prediction

In [92]:
y_pred = classifier.predict(x_test)

# 5. Evaluation

In [239]:
# accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.8106315230850876

In [240]:
# the confusion matrix
conf_metrics = metrics.confusion_matrix(y_test, y_pred)
conf_metrics

array([[9165, 2141],
       [   0,    0]], dtype=int64)

In [241]:
print(metrics.classification_report(y_test, y_pred))

# No. of features = 15

              precision    recall  f1-score   support

       <=50K       1.00      0.81      0.90     11306
        >50K       0.00      0.00      0.00         0

    accuracy                           0.81     11306
   macro avg       0.50      0.41      0.45     11306
weighted avg       1.00      0.81      0.90     11306



# 6. RFE to extract the best features.


In [101]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [102]:
regressor = LogisticRegression(solver='lbfgs')
rfe = RFE(regressor,4)
fit = rfe.fit(x_train, y_train)

In [103]:
temp_df = pd.DataFrame({'Columns' : x_train.columns, 'Included' : rfe.support_, 'Ranking' : rfe.ranking_})

temp_df

Columns  Included  Ranking
0                               age     False       38
1                   educational-num     False       13
2                      capital-gain      True        1
3                      capital-loss     False       57
4                    hours-per-week     False       37
..                              ...       ...      ...
98          native-country_Thailand     False       36
99   native-country_Trinadad&Tobago     False       20
100    native-country_United-States     False       51
101          native-country_Vietnam     False        4
102       native-country_Yugoslavia     False       47

[103 rows x 3 columns]

In [104]:
imp_col = x_train.columns[rfe.support_]
imp_col

Index(['capital-gain', 'marital-status_Married-civ-spouse',
       'occupation_Priv-house-serv', 'native-country_Mexico'],
      dtype='object')

In [105]:
x_train_new = x_train[imp_col]

x_train_new.head()

capital-gain  marital-status_Married-civ-spouse  \
36418     -0.146733                                0.0   
1080      -0.146733                                0.0   
17957     -0.146733                                1.0   
13607     -0.146733                                1.0   
43125     -0.146733                                0.0   

       occupation_Priv-house-serv  native-country_Mexico  
36418                         0.0                    0.0  
1080                          0.0                    0.0  
17957                         0.0                    0.0  
13607                         0.0                    0.0  
43125                         0.0                    0.0

In [106]:
from sklearn.linear_model import LogisticRegression
regressor_new = LogisticRegression()
regressor_new.fit(x_train_new, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [107]:
x_test_new = x_test[imp_col]

y_test_pred_new = regressor_new.predict(x_test_new)

In [108]:
temp_df_new = pd.DataFrame({'Actual': y_test, 'Predicted': y_test_pred_new})
temp_df_new

Actual Predicted
44688  <=50K     <=50K
38106  <=50K     <=50K
29131  <=50K     <=50K
31472   >50K     <=50K
45120  <=50K     <=50K
...      ...       ...
1915    >50K     <=50K
24393  <=50K     <=50K
31714  <=50K     <=50K
34235  <=50K     <=50K
10770  <=50K     <=50K

[11306 rows x 2 columns]

In [238]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_test_pred_new)

0.9415354678931541

In [110]:
# the confusion matrix
conf_metrics = metrics.confusion_matrix(y_test, y_test_pred_new)
conf_metrics

array([[8314,  153],
       [2331,  508]], dtype=int64)

Compare of the model

In [111]:
result_df = pd.DataFrame({'result_test': y_test, 'result_test_new': y_test_pred_new})

result_df.head()

result_test result_test_new
44688       <=50K           <=50K
38106       <=50K           <=50K
29131       <=50K           <=50K
31472        >50K           <=50K
45120       <=50K           <=50K

# 7. PCA (Principal Component Analysis)

## a.) Using Logistic Regression

In [150]:
# initializing the pca
from sklearn.decomposition import PCA
pca = PCA()

In [151]:
pca.fit(x_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [204]:
from sklearn.decomposition import PCA
pca_final = PCA(n_components = 15)
x_train = pca_final.fit_transform(x_train)

In [205]:
x_train.shape

(33916, 15)

In [206]:
x_test = pca_final.transform(x_test)

In [207]:
# building the final model with 15 features
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(x_train_pca, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [209]:
# coefficient and intercept
print(regressor_pca.coef_)
print(regressor_pca.intercept_)

[[ 0.01894131  0.00488033 -0.01068182  0.00399594  0.01008792 -0.01496467
  -0.00013776 -0.02240264  0.00523865  0.01632027 -0.03606798 -0.01599184
   0.02261319 -0.01338631  0.04108294]]
[-1.09682232]


In [210]:
# split into train and test 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df,\
                                                           target,\
                                                           test_size=0.25)

In [211]:
y_test = classifier.predict(x_test)

In [212]:
# accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.8499027065275075

In [218]:
# the confusion matrix
conf_metrics = metrics.confusion_matrix(y_test, y_test_pred_new)
conf_metrics

array([[10645,   661],
       [    0,     0]], dtype=int64)

In [219]:
# classification report
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       1.00      0.78      0.87     11306
        >50K       0.00      0.00      0.00         0

    accuracy                           0.78     11306
   macro avg       0.50      0.39      0.44     11306
weighted avg       1.00      0.78      0.87     11306



## b.) Using K-NN

In [220]:
# train the model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [222]:
# prediction
y_pred = classifier.predict(x_test)

In [223]:
# evaluation
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.7764019104900053

In [224]:
# the confusion matrix
conf_metrics = metrics.confusion_matrix(y_test, y_test_pred_new)
conf_metrics

array([[10645,   661],
       [    0,     0]], dtype=int64)

In [225]:
# classification report
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       1.00      0.78      0.87     11306
        >50K       0.00      0.00      0.00         0

    accuracy                           0.78     11306
   macro avg       0.50      0.39      0.44     11306
weighted avg       1.00      0.78      0.87     11306



## c.) Using DT 

In [226]:
# train the model
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth = 2)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [227]:
# prediction
y_pred = classifier.predict(x_test)

In [228]:
# evaluation
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.8521139218114275

In [229]:
# the confusion matrix
conf_metrics = metrics.confusion_matrix(y_test, y_test_pred_new)
conf_metrics

array([[10645,   661],
       [    0,     0]], dtype=int64)

In [233]:
# classification report
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       1.00      0.85      0.92     11306
        >50K       0.00      0.00      0.00         0

    accuracy                           0.85     11306
   macro avg       0.50      0.43      0.46     11306
weighted avg       1.00      0.85      0.92     11306



## d.) Using SVM

In [232]:
# train the model
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [234]:
# prediction
y_pred = classifier.predict(x_test)

In [235]:
# evaluation
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.8106315230850876

In [236]:
# the confusion matrix
conf_metrics = metrics.confusion_matrix(y_test, y_test_pred_new)
conf_metrics

array([[10645,   661],
       [    0,     0]], dtype=int64)

In [237]:
# classification report
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       1.00      0.81      0.90     11306
        >50K       0.00      0.00      0.00         0

    accuracy                           0.81     11306
   macro avg       0.50      0.41      0.45     11306
weighted avg       1.00      0.81      0.90     11306

